linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: chat-assistant-backend
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gocyclo
    - goconst
    - misspell
    - lll

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
