services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: chat-assistant-postgres
    environment:
      POSTGRES_DB: chat_assistant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Database Migration Service
  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    container_name: chat-assistant-migrate
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: chat_assistant
      DATABASE_SSLMODE: disable
    depends_on:
      postgres:
        condition: service_healthy
    command: [ "migrate", "-command", "up" ]
    volumes:
      - ./internal/migrations:/app/migrations
    profiles:
      - migrate

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: chat-assistant-network
