# Chat Assistant Backend Configuration
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "chat_assistant"
  sslmode: "disable"
  timezone: "UTC"
  max_open_conns: 25
  max_idle_conns: 25
  conn_max_lifetime: 5m

cors:
  allowed_origins: ["http://localhost:3000", "http://localhost:3001"]
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers: ["Origin", "Content-Type", "Accept", "Authorization", "X-Request-ID"]
  allow_credentials: true

logging:
  level: "info"  # debug, info, warn, error
  format: "json" # json, console
  output: "stdout" # stdout, stderr, file

import:
  batch_size: 100  # 批量导入的大小

i18n:
  default_language: "en"
  supported_languages: ["en", "zh"]

# Graceful shutdown timeout
shutdown_timeout: 30s
