// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"chat-assistant-backend/internal/config"
	"chat-assistant-backend/internal/handlers"
	"chat-assistant-backend/internal/repositories"
	"chat-assistant-backend/internal/server"
	"chat-assistant-backend/internal/services"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// InitializeApp initializes the application with all dependencies
func InitializeApp() (*server.Server, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	db, err := NewDatabase(configConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repositories.NewUserRepository(db)
	userService := services.NewUserService(userRepository)
	userHandler := handlers.NewUserHandler(userService)
	serverServer := NewServerWithDependencies(configConfig, db, userRepository, userService, userHandler)
	return serverServer, nil
}

// wire.go:

// NewDatabase creates a new database connection
func NewDatabase(cfg *config.Config) (*gorm.DB, error) {
	dsn := cfg.Database.GetDSN()
	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
	if err != nil {
		return nil, err
	}

	return db, nil
}

// NewServerWithDependencies creates a server with all dependencies injected
func NewServerWithDependencies(
	cfg *config.Config,
	db *gorm.DB,
	userRepo *repositories.UserRepository,
	userService *services.UserService,
	userHandler *handlers.UserHandler,
) *server.Server {
	return server.NewWithDependencies(cfg, db, userHandler)
}
